In [ ]:
import pandas as pd

In [ ]:
# Reemplaza tu línea actual por esta:
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
# Ver la estructura, número de filas, columnas y tipos de datos
df.info()

# Ver cuántos valores nulos (vacíos) hay por cada columna
print("Valores nulos por columna:")
print(df.isnull().sum())

# Resumen estadístico de las columnas numéricas (media, max, min, etc.)
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB
Valores nulos por columna:
ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [ ]:
# Eliminar ADDRESSLINE2 porque está casi vacía
df = df.drop(columns=['ADDRESSLINE2'])

In [ ]:
# Rellenar las demás columnas con un texto genérico
df['STATE'] = df['STATE'].fillna('N/A')
df['TERRITORY'] = df['TERRITORY'].fillna('Desconocido')
df['POSTALCODE'] = df['POSTALCODE'].fillna('00000')

# Verificamos que ya no queden nulos
print(df.isnull().sum())

ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
TERRITORY           0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
dtype: int64

In [ ]:
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'], errors='coerce')

# Verificamos el cambio
print(df['ORDERDATE'].dtypes)

datetime64[ns]

In [ ]:
# Eliminar duplicados si existen
df = df.drop_duplicates()

In [ ]:
df.to_csv('sales_data_clean.csv', index=False)

In [ ]:
# Ver la estructura, número de filas, columnas y tipos de datos
df.info()

# Ver cuántos valores nulos (vacíos) hay por cada columna
print("Valores nulos por columna:")
print(df.isnull().sum())

# Resumen estadístico de las columnas numéricas (media, max, min, etc.)
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   datetime64[ns]
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  CITY              2823 non-null   object
 17  STATE             2823 non-null   object
 18  POSTALCODE        2823 non-null   object
 19  COUNTRY           2823 non-null   object
 20  TERRITORY         2823 non-null   object
 21  CONTACTLASTNAME   2823 non-null   object
 22  CONTACTFIRSTNAME  2823 non-null   object
 23  DEALSIZE          2823 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(7), object(14)
memory usage: 529.4+ KB
Valores nulos por columna:
ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
TERRITORY           0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
dtype: int64

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2004-05-11 00:16:49.989373056,2.717676,7.092455,2003.81509,100.715551
min,10100.000000,6.000000,26.880000,1.000000,482.130000,2003-01-06 00:00:00,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2003-11-06 12:00:00,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,2004-06-15 00:00:00,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,2004-11-17 12:00:00,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,2005-05-31 00:00:00,4.000000,12.000000,2005.00000,214.000000
std,92.085478,9.741443,20.174277,4.225841,1841.865106,NaN,1.203878,3.656633,0.69967,40.187912

In [ ]:
# Convertir columnas de texto categóricas a minúsculas y remover espacios en blanco innecesarios
columnas_texto = ['STATUS', 'PRODUCTLINE', 'CUSTOMERNAME', 'CITY', 'COUNTRY', 'DEALSIZE']

for col in columnas_texto:
    df[col] = df[col].astype(str).str.lower().str.strip()

# Ejemplo: "  Shipped " ahora será estrictamente "shipped"
df['STATUS'].unique()

array(['shipped', 'disputed', 'in process', 'cancelled', 'on hold',
       'resolved'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   datetime64[ns]
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  CITY              2823 non-null   object
 17  STATE             2823 non-null   object
 18  POSTALCODE        2823 non-null   object
 19  COUNTRY           2823 non-null   object
 20  TERRITORY         2823 non-null   object
 21  CONTACTLASTNAME   2823 non-null   object
 22  CONTACTFIRSTNAME  2823 non-null   object
 23  DEALSIZE          2823 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(7), object(14)
memory usage: 529.4+ KB

In [ ]:
# Ver la estructura, número de filas, columnas y tipos de datos
df.info()

# Ver cuántos valores nulos (vacíos) hay por cada columna
print("Valores nulos por columna:")
print(df.isnull().sum())

# Resumen estadístico de las columnas numéricas (media, max, min, etc.)
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   datetime64[ns]
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  CITY              2823 non-null   object
 17  STATE             2823 non-null   object
 18  POSTALCODE        2823 non-null   object
 19  COUNTRY           2823 non-null   object
 20  TERRITORY         2823 non-null   object
 21  CONTACTLASTNAME   2823 non-null   object
 22  CONTACTFIRSTNAME  2823 non-null   object
 23  DEALSIZE          2823 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(7), object(14)
memory usage: 529.4+ KB
Valores nulos por columna:
ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
TERRITORY           0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
dtype: int64

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2004-05-11 00:16:49.989373056,2.717676,7.092455,2003.81509,100.715551
min,10100.000000,6.000000,26.880000,1.000000,482.130000,2003-01-06 00:00:00,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2003-11-06 12:00:00,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,2004-06-15 00:00:00,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,2004-11-17 12:00:00,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,2005-05-31 00:00:00,4.000000,12.000000,2005.00000,214.000000
std,92.085478,9.741443,20.174277,4.225841,1841.865106,NaN,1.203878,3.656633,0.69967,40.187912

In [ ]:
# Crear una fila de texto normalizado para que el RAG la indexe fácilmente
df['TEXT_CONTEXT'] = df.apply(lambda row:
    f"El cliente {row['CUSTOMERNAME']} de la ciudad de {row['CITY']}, {row['COUNTRY']}, "
    f"compró el producto con código {row['PRODUCTCODE']} (Línea: {row['PRODUCTLINE']}) "
    f"el día {row['ORDERDATE']}. Se ordenaron {row['QUANTITYORDERED']} unidades a un precio de "
    f"{row['PRICEEACH']} cada una, sumando un total de {row['SALES']} USD en ventas. "
    f"El estado actual del pedido es {row['STATUS']} y el tamaño del trato se clasifica como {row['DEALSIZE']}.",
    axis=1
)

# Ver cómo quedó tu texto normalizado para el Corpus
print(df['TEXT_CONTEXT'].iloc[0])

El cliente land of toys inc. de la ciudad de nyc, usa, compró el producto con código S10_1678 (Línea: motorcycles) el día 2003-02-24 00:00:00. Se ordenaron 30 unidades a un precio de 95.7 cada una, sumando un total de 2871.0 USD en ventas. El estado actual del pedido es shipped y el tamaño del trato se clasifica como small.

In [ ]:
# Create a normalized text row for easy RAG indexing
df['TEXT_CONTEXT'] = df.apply(lambda row:
    f"Customer {row['CUSTOMERNAME']} from the city of {row['CITY']}, {row['COUNTRY']}, "
    f"purchased the product with code {row['PRODUCTCODE']} (Line: {row['PRODUCTLINE']}) "
    f"on {row['ORDERDATE']}. A quantity of {row['QUANTITYORDERED']} units were ordered at a price of "
    f"{row['PRICEEACH']} each, totaling {row['SALES']} USD in sales. "
    f"The current status of the order is {row['STATUS']} and the deal size is classified as {row['DEALSIZE']}.",
    axis=1
)

# Check how your normalized text looks for the Corpus
print(df['TEXT_CONTEXT'].iloc[0])

Customer land of toys inc. from the city of nyc, usa, purchased the product with code S10_1678 (Line: motorcycles) on 2003-02-24 00:00:00. A quantity of 30 units were ordered at a price of 95.7 each, totaling 2871.0 USD in sales. The current status of the order is shipped and the deal size is classified as small.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   datetime64[ns]
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  CITY              2823 non-null   object
 17  STATE             2823 non-null   object
 18  POSTALCODE        2823 non-null   object
 19  COUNTRY           2823 non-null   object
 20  TERRITORY         2823 non-null   object
 21  CONTACTLASTNAME   2823 non-null   object
 22  CONTACTFIRSTNAME  2823 non-null   object
 23  DEALSIZE          2823 non-null   object
 24  TEXT_CONTEXT      2823 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(7), object(15)
memory usage: 551.5+ KB

In [ ]:
# Guardar el archivo definitivo
df.to_csv('sales_data_corpus_normalized.csv', index=False)

In [ ]:
# Versión en Español (Columna: TEXT_CONTEXT_ES)
df['TEXT_CONTEXT_ES'] = df.apply(lambda row:
    f"El cliente {row['CUSTOMERNAME']} de la ciudad de {row['CITY']}, {row['COUNTRY']}, "
    f"compró el producto con código {row['PRODUCTCODE']} (Línea: {row['PRODUCTLINE']}) "
    f"el día {row['ORDERDATE']}. Se ordenaron {row['QUANTITYORDERED']} unidades a un precio de "
    f"{row['PRICEEACH']} cada una, sumando un total de {row['SALES']} USD en ventas. "
    f"El estado actual del pedido es {row['STATUS']} y el tamaño del trato se clasifica como {row['DEALSIZE']}.",
    axis=1
)

# Versión en Inglés (Columna: TEXT_CONTEXT_EN)
df['TEXT_CONTEXT_EN'] = df.apply(lambda row:
    f"Customer {row['CUSTOMERNAME']} from the city of {row['CITY']}, {row['COUNTRY']}, "
    f"purchased the product with code {row['PRODUCTCODE']} (Line: {row['PRODUCTLINE']}) "
    f"on {row['ORDERDATE']}. A quantity of {row['QUANTITYORDERED']} units were ordered at a price of "
    f"{row['PRICEEACH']} each, totaling {row['SALES']} USD in sales. "
    f"The current status of the order is {row['STATUS']} and the deal size is classified as {row['DEALSIZE']}.",
    axis=1
)

# Ahora eliminamos la columna vieja ('TEXT_CONTEXT') que causaba confusión
if 'TEXT_CONTEXT' in df.columns:
    df = df.drop(columns=['TEXT_CONTEXT'])

# Verificamos que ahora tienes ambas columnas limpias e independientes
df[['TEXT_CONTEXT_ES', 'TEXT_CONTEXT_EN']].head(1)

,TEXT_CONTEXT_ES,TEXT_CONTEXT_EN
0,El cliente land of toys inc. de la ciudad de n...,Customer land of toys inc. from the city of ny...

In [ ]:
!pip install -qU langchain-mistralai langchain-community chromadb pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 90.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 60.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 99.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 15.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 74.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 51.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.1/548.1 kB 33.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 73.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 3.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.42.0 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.42.0 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.0 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.3 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.42.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.42.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.42.0 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.

In [ ]:
import os
from google.colab import userdata

# Esto lee la clave de forma segura desde los secretos de tu Colab
os.environ["MISTRAL_API_KEY"] = userdata.get('MISTRAL_API_KEY')

In [ ]:
from langchain_community.document_loaders import DataFrameLoader
from langchain_mistralai import MistralAIEmbeddings
from langchain_community.vectorstores import Chroma

# 1. Cargamos la columna en español como los "documentos" del RAG
loader = DataFrameLoader(df, page_content_column="TEXT_CONTEXT_ES")
documentos = loader.load()

# 2. Inicializamos los "Embeddings" (el traductor de texto a vectores de Mistral)
embeddings = MistralAIEmbeddings(model="mistral-embed")

# 3. Creamos la base de datos vectorial en la memoria de Colab
vector_store = Chroma.from_documents(documentos, embeddings)

print("¡Corpus indexado con éxito! El RAG ya puede buscar en tus ventas.")

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

# 1. Cargamos el archivo de nuevo con la codificación correcta
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# 2. Limpieza de nulos y columnas innecesarias
df = df.drop(columns=['ADDRESSLINE2', 'PHONE', 'ADDRESSLINE1', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME'], errors='ignore')
df['STATE'] = df['STATE'].fillna('N/A')
df['TERRITORY'] = df['TERRITORY'].fillna('Desconocido')
df['POSTALCODE'] = df['POSTALCODE'].fillna('00000')
df = df.drop_duplicates()

# 3. Normalización (Textos a minúsculas y formato de fecha)
columnas_texto = ['STATUS', 'PRODUCTLINE', 'CUSTOMERNAME', 'CITY', 'COUNTRY', 'DEALSIZE']
for col in columnas_texto:
    df[col] = df[col].astype(str).str.lower().str.strip()

df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE']).dt.strftime('%Y-%m-%d')

# 4. Creamos la columna en español para el Corpus
df['TEXT_CONTEXT_ES'] = df.apply(lambda row:
    f"El cliente {row['CUSTOMERNAME']} de la ciudad de {row['CITY']}, {row['COUNTRY']}, "
    f"compró el producto con código {row['PRODUCTCODE']} (Línea: {row['PRODUCTLINE']}) "
    f"el día {row['ORDERDATE']}. Se ordenaron {row['QUANTITYORDERED']} unidades a un precio de "
    f"{row['PRICEEACH']} cada una, sumando un total de {row['SALES']} USD en ventas. "
    f"El estado actual del pedido es {row['STATUS']} y el tamaño del trato se clasifica como {row['DEALSIZE']}.",
    axis=1
)

print("¡Dataset 'df' reestablecido y normalizado con éxito!")

¡Dataset 'df' reestablecido y normalizado con éxito!

In [ ]:
!pip install -qU langchain==0.1.16 langchain-community==0.0.34 langchain-mistralai chromadb pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 817.7/817.7 kB 27.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 40.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.1/303.1 kB 18.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.8/311.8 kB 15.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 33.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-classic 1.0.7 requires langchain-core<2.0.0,>=1.3.3, but you have langchain-core 0.1.53 which is incompatible.
langchain-classic 1.0.7 requires langchain-text-splitters<2.0.0,>=1.1.2, but you have langchain-text-splitters 0.0.2 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
google-cloud-bigquery 3.41.0 requires packaging>=24.2.0, but you have packaging 23.2 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.42.0 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.0 which is incompatible.
google-adk 1.29.0 requires tenacity<10.0.0,>=9.0.0, but you have tenacity 8.5.0 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
langgraph 1.1.9 requires langchain-core<2,>=1.3.0, but you have langchain-core 0.1.53 which is incompatible.
langgraph-checkpoint 4.0.2 requires langchain-core>=0.2.38, but you have langchain-core 0.1.53 which is incompatible.
wheel 0.47.0 requires packaging>=24.0, but you have packaging 23.2 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
bigquery-magics 0.14.0 requires packaging>=24.2.0, but you have packaging 23.2 which is incompatible.
langgraph-prebuilt 1.0.10 requires langchain-core>=1.0.0, but you have langchain-core 0.1.53 which is incompatible.
xarray 2025.12.0 requires packaging>=24.1, but you have packaging 23.2 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.3 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
db-dtypes 1.5.1 requires packaging>=24.2.0, but you have packaging 23.2 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.

In [ ]:
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.tools import create_retriever_tool
from langchain_mistralai import ChatMistralAI
from langchain.agents import AgentExecutor, create_openai_tools_agent
# Si el de arriba falla, LangChain ahora obliga a usar la sintaxis moderna de abajo:
from langchain.agents.initialize import initialize_agent

# 1. Convertimos nuestro RAG en una herramienta para el agente
retriever = vector_store.as_retriever(search_kwargs={"k": 3})
tool_rag = create_retriever_tool(
    retriever,
    "buscar_en_ventas",
    "Úsala para buscar información detallada sobre las ventas, clientes, productos, pedidos, países y estados de cuenta."
)
tools = [tool_rag]

# 2. Inicializamos Mistral
llm = ChatMistralAI(model="mistral-small-latest", temperature=0)

# 3. Usamos el inicializador universal de agentes (que es súper estable ante cambios de versión)
agente_ventas = initialize_agent(
    tools=tools,
    llm=llm,
    agent="openai-tools", # Estándar compatible con Mistral para llamadas de herramientas
    verbose=True,
    agent_kwargs={
        "system_message": "Eres un asistente experto en análisis de datos de ventas de la empresa. "
                          "Responde las preguntas del usuario basándote SIEMPRE en la información que encuentres usando la herramienta 'buscar_en_ventas'. "
                          "Si no encuentras la información con la herramienta, di amablemente que no posees esos registros. "
                          "Responde siempre en español de forma clara, profesional y concisa."
    }
)

print("¡Agente de Inteligencia Artificial configurado con el método estable!")

/usr/local/lib/python3.12/dist-packages/langgraph/checkpoint/serde/encrypted.py:5: LangChainPendingDeprecationWarning: The default value of `allowed_objects` will change in a future version. Pass an explicit value (e.g., allowed_objects='messages' or allowed_objects='core') to suppress this warning.
  from langgraph.checkpoint.serde.jsonplus import JsonPlusSerializer

ImportError: cannot import name 'AgentExecutor' from 'langchain.agents' (/usr/local/lib/python3.12/dist-packages/langchain/agents/__init__.py)

In [ ]:
!pip install -qU langchain langchain-community langchain-mistralai chromadb pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.3/114.3 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.3/234.3 kB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.6/399.6 kB 20.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.0/56.0 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 2.8 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import os
from google.colab import userdata
from langchain_community.document_loaders import DataFrameLoader
from langchain_mistralai import MistralAIEmbeddings
from langchain_community.vectorstores import Chroma

# ==========================================
# 1. CARGAR Y NORMALIZAR EL DATASET
# ==========================================
print("⏳ Cargando y normalizando el archivo CSV...")
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# Limpieza de nulos y columnas innecesarias
df = df.drop(columns=['ADDRESSLINE2', 'PHONE', 'ADDRESSLINE1', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME'], errors='ignore')
df['STATE'] = df['STATE'].fillna('N/A')
df['TERRITORY'] = df['TERRITORY'].fillna('Desconocido')
df['POSTALCODE'] = df['POSTALCODE'].fillna('00000')
df = df.drop_duplicates()

# Normalizar textos a minúsculas y fechas
columnas_texto = ['STATUS', 'PRODUCTLINE', 'CUSTOMERNAME', 'CITY', 'COUNTRY', 'DEALSIZE']
for col in columnas_texto:
    df[col] = df[col].astype(str).str.lower().str.strip()

df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE']).dt.strftime('%Y-%m-%d')

# Crear la columna de contexto en español para el Corpus RAG
df['TEXT_CONTEXT_ES'] = df.apply(lambda row:
    f"El cliente {row['CUSTOMERNAME']} de la ciudad de {row['CITY']}, {row['COUNTRY']}, "
    f"compró el producto con código {row['PRODUCTCODE']} (Línea: {row['PRODUCTLINE']}) "
    f"el día {row['ORDERDATE']}. Se ordenaron {row['QUANTITYORDERED']} unidades a un precio de "
    f"{row['PRICEEACH']} cada una, sumando un total de {row['SALES']} USD en ventas. "
    f"El estado actual del pedido es {row['STATUS']} y el tamaño del trato se clasifica como {row['DEALSIZE']}.",
    axis=1
)
print("✅ Dataset 'df' procesado correctamente.")

# ==========================================
# 2. CONFIGURAR LA API KEY DE MISTRAL
# ==========================================
# Esto lee la clave desde el ícono de la llave 🔑 de tu barra lateral izquierda de Colab
os.environ["MISTRAL_API_KEY"] = userdata.get('MISTRAL_API_KEY')
print("✅ API Key de Mistral cargada desde Secrets.")

# ==========================================
# 3. CREAR EL CORPUS VECTORIAL (EL RAG)
# ==========================================
print("⏳ Indexando los datos en la base de datos vectorial (RAG)...")
loader = DataFrameLoader(df, page_content_column="TEXT_CONTEXT_ES")
documentos = loader.load()

# Inicializamos los embeddings de Mistral y guardamos en memoria con Chroma
embeddings = MistralAIEmbeddings(model="mistral-embed")
vector_store = Chroma.from_documents(documentos, embeddings)

print("🚀 ¡Todo listo! El dataset y el RAG están activos en la memoria.")

⏳ Cargando y normalizando el archivo CSV...
✅ Dataset 'df' procesado correctamente.
✅ API Key de Mistral cargada desde Secrets.
⏳ Indexando los datos en la base de datos vectorial (RAG)...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer.json: 0.00B [00:00, ?B/s]

🚀 ¡Todo listo! El dataset y el RAG están activos en la memoria.

In [4]:
from langchain_core.tools import create_retriever_tool
from langchain_mistralai import ChatMistralAI
from langchain_core.messages import HumanMessage, ToolMessage, SystemMessage

# 1. Convertimos el RAG en una herramienta oficial de LangChain
retriever = vector_store.as_retriever(search_kwargs={"k": 3})
tool_rag = create_retriever_tool(
    retriever,
    "buscar_en_ventas",
    "Úsala para buscar información detallada sobre las ventas, clientes, productos, pedidos, países y estados de cuenta."
)

# 2. Inicializamos el modelo de Mistral y le "enlazamos" la herramienta (Sintaxis moderna)
llm = ChatMistralAI(model="mistral-small-latest", temperature=0)
llm_con_herramientas = llm.bind_tools([tool_rag])

# 3. El Orquestador del Agente (La lógica que reemplaza de forma limpia al viejo AgentExecutor)
def ejecutar_agente_langchain(pregunta_usuario: str):
    print(f"**Pregunta del Usuario:** {pregunta_usuario}\n")

    # Historial de mensajes con las instrucciones del sistema
    messages = [
        SystemMessage(content="Eres un asistente experto en análisis de datos de ventas de la empresa. "
                             "Responde siempre en español de forma clara, profesional y concisa basándote en la herramienta 'buscar_en_ventas'."),
        HumanMessage(content=pregunta_usuario)
    ]

    # Primer pase: El modelo evalúa la pregunta
    respuesta_modelo = llm_con_herramientas.invoke(messages)

    # ¿El modelo decidió que necesita buscar en el RAG?
    if respuesta_modelo.tool_calls:
        print("🤖 [Agente LangChain]: Necesito buscar datos. Activando herramienta...")
        messages.append(respuesta_modelo)

        for tool_call in respuesta_modelo.tool_calls:
            # Ejecutar la búsqueda en el vector_store usando la herramienta de LangChain
            print(f"🔍 [RAG]: Buscando registros relacionados con '{tool_call['args']['query']}'...")
            resultado_txt = tool_rag.invoke(tool_call['args'])

            # Guardamos la respuesta de la herramienta en el flujo
            messages.append(ToolMessage(content=resultado_txt, tool_call_id=tool_call['id']))

        # Segundo pase: Mistral lee el Corpus recuperado y redacta la respuesta final
        print("✍️ [Mistral]: Procesando datos extraídos del Corpus...")
        respuesta_final = llm_con_herramientas.invoke(messages)
        return respuesta_final.content
    else:
        # Si fue una pregunta simple o saludo, responde directo
        return respuesta_modelo.content

print("¡Agente con arquitectura LangChain moderna configurado con éxito!")

NameError: name 'vector_store' is not defined

In [3]:
!pip install -qU langchain-mistralai

In [5]:
from langchain_community.document_loaders import DataFrameLoader
from langchain_mistralai import MistralAIEmbeddings, ChatMistralAI
from langchain_community.vectorstores import Chroma
from langchain_core.tools import create_retriever_tool
from langchain_core.messages import HumanMessage, ToolMessage, SystemMessage

# ========================================================
# 1. CREAR EL CORPUS VECTORIAL (EL RAG)
# ========================================================
print("⏳ Generando los vectores del Corpus en la memoria...")
loader = DataFrameLoader(df, page_content_column="TEXT_CONTEXT_ES")
documentos = loader.load()

# Inicializamos los embeddings oficiales de Mistral
embeddings = MistralAIEmbeddings(model="mistral-embed")
# Creamos la base de datos vectorial asignándola a la variable vector_store
vector_store = Chroma.from_documents(documentos, embeddings)
print("✅ Base de datos vectorial 'vector_store' creada con éxito.")


# ========================================================
# 2. CONFIGURAR LA HERRAMIENTA Y EL MODELO MISTRAL
# ========================================================
# Ahora que existe vector_store, creamos el retriever sin perder la variable
retriever = vector_store.as_retriever(search_kwargs={"k": 3})
tool_rag = create_retriever_tool(
    retriever,
    "buscar_en_ventas",
    "Úsala para buscar información detallada sobre las ventas, clientes, productos, pedidos, países y estados de cuenta."
)

# Inicializamos Mistral y le enlazamos la herramienta
llm = ChatMistralAI(model="mistral-small-latest", temperature=0)
llm_con_herramientas = llm.bind_tools([tool_rag])
print("✅ Herramientas vinculadas a Mistral.")


# ========================================================
# 3. EL ORQUESTADOR DEL AGENTE MODERNO
# ========================================================
def ejecutar_agente_langchain(pregunta_usuario: str):
    print(f"\n💬 **Pregunta del Usuario:** {pregunta_usuario}\n")

    messages = [
        SystemMessage(content="Eres un asistente experto en análisis de datos de ventas de la empresa. "
                             "Responde siempre en español de forma clara, profesional y concisa basándote en la herramienta 'buscar_en_ventas'."),
        HumanMessage(content=pregunta_usuario)
    ]

    # Evaluar la pregunta con Mistral
    respuesta_modelo = llm_con_herramientas.invoke(messages)

    # Si el agente decide usar el RAG
    if respuesta_modelo.tool_calls:
        print("🤖 [Agente]: Necesito buscar datos en el Corpus. Activando herramienta...")
        messages.append(respuesta_modelo)

        for tool_call in respuesta_modelo.tool_calls:
            print(f"🔍 [RAG]: Recuperando registros para '{tool_call['args']['query']}'...")
            resultado_txt = tool_rag.invoke(tool_call['args'])
            messages.append(ToolMessage(content=resultado_txt, tool_call_id=tool_call['id']))

        print("✍️ [Mistral]: Redactando respuesta final basada en el CSV...")
        respuesta_final = llm_con_herramientas.invoke(messages)
        return respuesta_final.content
    else:
        return respuesta_modelo.content

print("\n🚀 ¡TODO LISTO! Estructura LangChain acoplada y lista para interrogar.")

ModuleNotFoundError: No module named 'langchain_community'