In [ ]:
import pandas as pd
df = pd.read_csv('dataset2.csv', encoding='latin1', index_col=0)

In [ ]:
df.head(20)

,Nombre y Apellido,MatemÃ¡tica,FÃ­sica,ProgramaciÃ³n,Lengua,EstadÃ­stica,Historia y Geografia,Castellano,Educacion etica,Geometria
Nro de documento,,,,,,,,,,
10234567,Juan PÃ©rez,5.0,5.0,5.0,5,5.0,5.0,5.0,5,5
11890123,MarÃ­a GarcÃ­a,2.0,2.0,3.0,4,2.0,4.0,5.0,3,2
12456789,Carlos LÃ³pez,5.0,4.0,5.0,3,4.0,4.0,3.0,4,5
13321654,Ana RodrÃ­guez,1.0,2.0,2.0,3,2.0,3.0,3.0,2,2
14789012,Luis MartÃ­nez,3.0,3.0,4.0,4,5.0,5.0,4.0,4,3
15147258,Elena GÃ³mez,5.0,5.0,5.0,5,4.0,4.0,5.0,5,5
16963852,Diego Torres,2.0,1.0,3.0,2,1.0,2.0,3.0,2,1
17159357,SofÃ­a Castro,4.0,4.0,3.0,5,4.0,5.0,5.0,4,4
18753159,Javier Ruiz,3.0,2.0,4.0,3,3.0,4.0,3.0,3,3
19456123,LucÃ­a Morales,4.0,5.0,4.0,4,5.0,4.0,4.0,5,4
10234567,JUAN PEREZ,5.0,5.0,5.0,5,5.0,5.0,5.0,5,5
20567890,marcos benitez,3.0,NaN,2.0,4,3.0,2.0,4.0,3,2
21456789,Valentina Alonso,4.0,4.0,4.0,5,NaN,5.0,4.0,4,4
22345678,ramiro sosa,1.0,1.0,1.0,2,1.0,2.0,2.0,1,1
23123456,Marta QuiÃ±Ã³nez,5.0,4.0,3.0,5,5.0,4.0,5.0,5,5
24987654,victor romero,2.0,3.0,2.0,3,2.0,NaN,3.0,2,2
25874136,Gabriela Duarte,4.0,4.0,5.0,4,4.0,4.0,4.0,5,4
26741258,raul villalba,3.0,2.0,3.0,3,3.0,3.0,3.0,3,3
27418529,ESTELA MEZA,5.0,5.0,5.0,5,5.0,5.0,5.0,5,5
28529637,hugo cardozo,2.0,2.0,2.0,2,2.0,2.0,2.0,2,2

In [ ]:
print(df.info())
print(df.head)

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 10234567 to 58765432
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Nombre y Apellido     50 non-null     object
 1   MatemÃ¡tica           49 non-null     float64
 2   FÃ­sica               49 non-null     float64
 3   ProgramaciÃ³n         49 non-null     float64
 4   Lengua                50 non-null     int64
 5   EstadÃ­stica          49 non-null     float64
 6   Historia y Geografia  49 non-null     float64
 7   Castellano            49 non-null     float64
 8   Educacion etica       50 non-null     int64
 9   Geometria             50 non-null     int64
dtypes: float64(6), int64(3), object(1)
memory usage: 4.3+ KB
None
<bound method NDFrame.head of                   Nombre y Apellido  MatemÃ¡tica  FÃ­sica  ProgramaciÃ³n  \
Nro de documento
10234567                Juan PÃ©rez          5.0      5.0            5.0
11890123             MarÃ­a GarcÃ­a          2.0      2.0            3.0
12456789              Carlos LÃ³pez          5.0      4.0            5.0
13321654             Ana RodrÃ­guez          1.0      2.0            2.0
14789012             Luis MartÃ­nez          3.0      3.0            4.0
15147258               Elena GÃ³mez          5.0      5.0            5.0
16963852               Diego Torres          2.0      1.0            3.0
17159357              SofÃ­a Castro          4.0      4.0            3.0
18753159                Javier Ruiz          3.0      2.0            4.0
19456123             LucÃ­a Morales          4.0      5.0            4.0
10234567                 JUAN PEREZ          5.0      5.0            5.0
20567890             marcos benitez          3.0      NaN            2.0
21456789          Valentina  Alonso          4.0      4.0            4.0
22345678                ramiro sosa          1.0      1.0            1.0
23123456           Marta QuiÃ±Ã³nez          5.0      4.0            3.0
24987654              victor romero          2.0      3.0            2.0
25874136            Gabriela Duarte          4.0      4.0            5.0
26741258              raul villalba          3.0      2.0            3.0
27418529                ESTELA MEZA          5.0      5.0            5.0
28529637               hugo cardozo          2.0      2.0            2.0
13321654             Ana RodrÃ­guez          1.0      2.0            2.0
30123456            fabian amarilla          4.0      3.0            4.0
31234567              lorenza gauto          NaN      5.0            5.0
32345678                PEDRO GOMEZ          3.0      3.0            3.0
33456789            lucia fernandez          2.0      2.0            2.0
34567890           Oscar  Alvarenga          4.0      4.0            4.0
35678901             mabel riquelme          5.0      5.0            5.0
36789012             jorge espinola          1.0      1.0            1.0
37890123               CYNTHIA VERA          3.0      3.0            3.0
38901234            ricardo fleitas          4.0      4.0            4.0
38901234            ricardo fleitas          4.0      4.0            4.0
40123456              Sandra Bogado          5.0      5.0            NaN
41234567           cristian ocampos          2.0      2.0            2.0
42345678              NIDIA GIMENEZ          3.0      3.0            4.0
43456789          sergio  caballero          4.0      5.0            4.0
44567890             BLANCA SILVERO          5.0      5.0            5.0
45678901             gustavo adorno          1.0      1.0            1.0
46789012             mirta arguello          2.0      3.0            2.0
47890123               ALDO  ZARATE          4.0      4.0            4.0
48901234             karina sanchez          3.0      3.0            3.0
49012345           ignacio portillo          5.0      5.0            5.0
50123456            SONIA FLORENTIN          2.0      2.0            2.0
51234567              ramon caceres          4.0      4.0            4.0
52345678             silvia  valdez          3.0      3.0            3.0
19456123             LucÃ­a Morales          4.0      5.0            4.0
54321098             MARCELO  RIVAS          5.0      4.0            5.0
55432109           patricia galeano          2.0      2.0            1.0
56543210           CLAUDIO  MENDOZA          4.0      3.0            4.0
57654321             beatriz oviedo          3.0      3.0            3.0
58765432              ENRIQUE AYALA          5.0      5.0            5.0

                  Lengua  EstadÃ­stica  Historia y Geografia  Castellano  \
Nro de documento
10234567               5           5.0                   5.0         5.0
11890123               4           2.0                   4.0         5.0
12456789               3           4.0                   4.0         3.0
13321654               3           2.0                   3.0         3.0
14789012               4           5.0                   5.0         4.0
15147258               5           4.0                   4.0         5.0
16963852               2           1.0                   2.0         3.0
17159357               5           4.0                   5.0         5.0
18753159               3           3.0                   4.0         3.0
19456123               4           5.0                   4.0         4.0
10234567               5           5.0                   5.0         5.0
20567890               4           3.0                   2.0         4.0
21456789               5           NaN                   5.0         4.0
22345678               2           1.0                   2.0         2.0
23123456               5           5.0                   4.0         5.0
24987654               3           2.0                   NaN         3.0
25874136               4           4.0                   4.0         4.0
26741258               3           3.0                   3.0         3.0
27418529               5           5.0                   5.0         5.0
28529637               2           2.0                   2.0         2.0
13321654               3           2.0                   3.0         3.0
30123456               4           4.0                   4.0         4.0
31234567               5           5.0                   5.0         5.0
32345678               3           3.0                   3.0         3.0
33456789               1           2.0                   2.0         2.0
34567890               4           4.0                   4.0         4.0
35678901               5           5.0                   5.0         5.0
36789012               2           1.0                   2.0         1.0
37890123               3           4.0                   3.0         3.0
38901234               4           4.0                   4.0         4.0
38901234               4           4.0                   4.0         4.0
40123456               5           5.0                   5.0         5.0
41234567               2           2.0                   2.0         2.0
42345678               3           3.0                   3.0         3.0
43456789               4           4.0                   4.0         4.0
44567890               5           5.0                   5.0         5.0
45678901               1           1.0                   1.0         1.0
46789012               2           2.0                   2.0         2.0
47890123               4           4.0                   4.0         4.0
48901234               3           3.0                   3.0         3.0
49012345               5           5.0                   5.0         NaN
50123456               2           2.0                   2.0         2.0
51234567               4           4.0                   4.0         4.0
52345678               3           3.0                   3.0         3.0
19456123               4           5.0                   4.0         4.0
54321098               5           5.0                   5.0         5.0
55432109               2           2.0                   2.0         2.0
56543210               4           4.0                   4.0         4.0
57654321               3           3.0                   3.0         3.0
58765432               5           5.0                   5.0         5.0

                  Educacion etica  Geometria
Nro de documento
10234567                        5          5
11890123                        3          2
12456789                        4          5
13321654                        2          2
14789012                        4          3
15147258                        5          5
16963852                        2          1
17159357                        4          4
18753159                        3          3
19456123                        5          4
10234567                        5          5
20567890                        3          2
21456789                        4          4
22345678                        1          1
23123456                        5          5
24987654                        2          2
25874136                        5          4
26741258                        3          3
27418529                        5          5
28529637                        2          2
13321654                        2          2
30123456                        4          4
31234567                        5          5
32345678                        3          3
33456789                        2          2
34567890                        4          4
35678901                        5          5
36789012                        1          1
37890123                        3          3
38901234                        4          4
38901234                        4          4
40123456                        5          5
41234567                        2          2
42345678                        3          3
43456789                        4          4
44567890                        5          5
45678901                        1          1
46789012                        2          2
47890123                        4          4
48901234                        3          3
49012345                        5          5
50123456                        2          2
51234567                        4          4
52345678                        3          3
19456123                        5          4
54321098                        5          5
55432109                        2          2
56543210                        4          4
57654321                        3          3
58765432                        5          5  >

In [ ]:
print(df.head)

<bound method NDFrame.head of                   Nombre y Apellido  MatemÃ¡tica  FÃ­sica  ProgramaciÃ³n  \
Nro de documento
10234567                Juan PÃ©rez          5.0      5.0            5.0
11890123             MarÃ­a GarcÃ­a          2.0      2.0            3.0
12456789              Carlos LÃ³pez          5.0      4.0            5.0
13321654             Ana RodrÃ­guez          1.0      2.0            2.0
14789012             Luis MartÃ­nez          3.0      3.0            4.0
15147258               Elena GÃ³mez          5.0      5.0            5.0
16963852               Diego Torres          2.0      1.0            3.0
17159357              SofÃ­a Castro          4.0      4.0            3.0
18753159                Javier Ruiz          3.0      2.0            4.0
19456123             LucÃ­a Morales          4.0      5.0            4.0
10234567                 JUAN PEREZ          5.0      5.0            5.0
20567890             marcos benitez          3.0      NaN            2.0
21456789          Valentina  Alonso          4.0      4.0            4.0
22345678                ramiro sosa          1.0      1.0            1.0
23123456           Marta QuiÃ±Ã³nez          5.0      4.0            3.0
24987654              victor romero          2.0      3.0            2.0
25874136            Gabriela Duarte          4.0      4.0            5.0
26741258              raul villalba          3.0      2.0            3.0
27418529                ESTELA MEZA          5.0      5.0            5.0
28529637               hugo cardozo          2.0      2.0            2.0
13321654             Ana RodrÃ­guez          1.0      2.0            2.0
30123456            fabian amarilla          4.0      3.0            4.0
31234567              lorenza gauto          NaN      5.0            5.0
32345678                PEDRO GOMEZ          3.0      3.0            3.0
33456789            lucia fernandez          2.0      2.0            2.0
34567890           Oscar  Alvarenga          4.0      4.0            4.0
35678901             mabel riquelme          5.0      5.0            5.0
36789012             jorge espinola          1.0      1.0            1.0
37890123               CYNTHIA VERA          3.0      3.0            3.0
38901234            ricardo fleitas          4.0      4.0            4.0
38901234            ricardo fleitas          4.0      4.0            4.0
40123456              Sandra Bogado          5.0      5.0            NaN
41234567           cristian ocampos          2.0      2.0            2.0
42345678              NIDIA GIMENEZ          3.0      3.0            4.0
43456789          sergio  caballero          4.0      5.0            4.0
44567890             BLANCA SILVERO          5.0      5.0            5.0
45678901             gustavo adorno          1.0      1.0            1.0
46789012             mirta arguello          2.0      3.0            2.0
47890123               ALDO  ZARATE          4.0      4.0            4.0
48901234             karina sanchez          3.0      3.0            3.0
49012345           ignacio portillo          5.0      5.0            5.0
50123456            SONIA FLORENTIN          2.0      2.0            2.0
51234567              ramon caceres          4.0      4.0            4.0
52345678             silvia  valdez          3.0      3.0            3.0
19456123             LucÃ­a Morales          4.0      5.0            4.0
54321098             MARCELO  RIVAS          5.0      4.0            5.0
55432109           patricia galeano          2.0      2.0            1.0
56543210           CLAUDIO  MENDOZA          4.0      3.0            4.0
57654321             beatriz oviedo          3.0      3.0            3.0
58765432              ENRIQUE AYALA          5.0      5.0            5.0

                  Lengua  EstadÃ­stica  Historia y Geografia  Castellano  \
Nro de documento
10234567               5           5.0                   5.0         5.0
11890123               4           2.0                   4.0         5.0
12456789               3           4.0                   4.0         3.0
13321654               3           2.0                   3.0         3.0
14789012               4           5.0                   5.0         4.0
15147258               5           4.0                   4.0         5.0
16963852               2           1.0                   2.0         3.0
17159357               5           4.0                   5.0         5.0
18753159               3           3.0                   4.0         3.0
19456123               4           5.0                   4.0         4.0
10234567               5           5.0                   5.0         5.0
20567890               4           3.0                   2.0         4.0
21456789               5           NaN                   5.0         4.0
22345678               2           1.0                   2.0         2.0
23123456               5           5.0                   4.0         5.0
24987654               3           2.0                   NaN         3.0
25874136               4           4.0                   4.0         4.0
26741258               3           3.0                   3.0         3.0
27418529               5           5.0                   5.0         5.0
28529637               2           2.0                   2.0         2.0
13321654               3           2.0                   3.0         3.0
30123456               4           4.0                   4.0         4.0
31234567               5           5.0                   5.0         5.0
32345678               3           3.0                   3.0         3.0
33456789               1           2.0                   2.0         2.0
34567890               4           4.0                   4.0         4.0
35678901               5           5.0                   5.0         5.0
36789012               2           1.0                   2.0         1.0
37890123               3           4.0                   3.0         3.0
38901234               4           4.0                   4.0         4.0
38901234               4           4.0                   4.0         4.0
40123456               5           5.0                   5.0         5.0
41234567               2           2.0                   2.0         2.0
42345678               3           3.0                   3.0         3.0
43456789               4           4.0                   4.0         4.0
44567890               5           5.0                   5.0         5.0
45678901               1           1.0                   1.0         1.0
46789012               2           2.0                   2.0         2.0
47890123               4           4.0                   4.0         4.0
48901234               3           3.0                   3.0         3.0
49012345               5           5.0                   5.0         NaN
50123456               2           2.0                   2.0         2.0
51234567               4           4.0                   4.0         4.0
52345678               3           3.0                   3.0         3.0
19456123               4           5.0                   4.0         4.0
54321098               5           5.0                   5.0         5.0
55432109               2           2.0                   2.0         2.0
56543210               4           4.0                   4.0         4.0
57654321               3           3.0                   3.0         3.0
58765432               5           5.0                   5.0         5.0

                  Educacion etica  Geometria
Nro de documento
10234567                        5          5
11890123                        3          2
12456789                        4          5
13321654                        2          2
14789012                        4          3
15147258                        5          5
16963852                        2          1
17159357                        4          4
18753159                        3          3
19456123                        5          4
10234567                        5          5
20567890                        3          2
21456789                        4          4
22345678                        1          1
23123456                        5          5
24987654                        2          2
25874136                        5          4
26741258                        3          3
27418529                        5          5
28529637                        2          2
13321654                        2          2
30123456                        4          4
31234567                        5          5
32345678                        3          3
33456789                        2          2
34567890                        4          4
35678901                        5          5
36789012                        1          1
37890123                        3          3
38901234                        4          4
38901234                        4          4
40123456                        5          5
41234567                        2          2
42345678                        3          3
43456789                        4          4
44567890                        5          5
45678901                        1          1
46789012                        2          2
47890123                        4          4
48901234                        3          3
49012345                        5          5
50123456                        2          2
51234567                        4          4
52345678                        3          3
19456123                        5          4
54321098                        5          5
55432109                        2          2
56543210                        4          4
57654321                        3          3
58765432                        5          5  >

,Nro de documento,Nombre y Apellido,MatemÃ¡tica,FÃ­sica,ProgramaciÃ³n,Lengua,EstadÃ­stica,Historia y Geografia,Castellano,Educacion etica,Geometria
0,10234567,Juan PÃ©rez,5.0,5.0,5.0,5,5.0,5.0,5.0,5,5
1,11890123,MarÃ­a GarcÃ­a,2.0,2.0,3.0,4,2.0,4.0,5.0,3,2
2,12456789,Carlos LÃ³pez,5.0,4.0,5.0,3,4.0,4.0,3.0,4,5
3,13321654,Ana RodrÃ­guez,1.0,2.0,2.0,3,2.0,3.0,3.0,2,2
4,14789012,Luis MartÃ­nez,3.0,3.0,4.0,4,5.0,5.0,4.0,4,3

In [ ]:
# Esta forma es segura de correr muchas veces
cols_a_borrar = ['Unnamed: 0']

# Solo borra si la columna realmente existe en el dataframe actual
df = df.drop(columns=[c for c in cols_a_borrar if c in df.columns])

In [ ]:
# Esto te mostrará los valores únicos en la columna 'Matematica'
print(df['MatemÃ¡tica'].unique())

[ 5.  2.  1.  3.  4. nan]